"""Create a simple obstacle-warning visualization for one image.

The script expects an RGB image and the disparity npy file generated by
monodepth2/test_simple.py or lite-mono/test_simple.py.
"""

import argparse
import os

import cv2
import numpy as np


STATUS_COLORS = {
    "SAFE": (64, 180, 80),
    "CAUTION": (0, 190, 255),
    "DANGER": (40, 40, 220),
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Overlay a front-area obstacle warning on one image."
    )
    parser.add_argument("--image_path", required=True, help="Path to the input image.")
    parser.add_argument(
        "--disp_path",
        default=None,
        help="Path to *_disp.npy. Defaults to <image_name>_disp.npy.",
    )
    parser.add_argument(
        "--output_path",
        default=None,
        help="Output image path. Defaults to <image_name>_warning.jpg.",
    )
    parser.add_argument("--roi_x1", type=float, default=0.33)
    parser.add_argument("--roi_x2", type=float, default=0.67)
    parser.add_argument("--roi_y1", type=float, default=0.40)
    parser.add_argument("--roi_y2", type=float, default=0.78)
    parser.add_argument(
        "--near_percentile",
        type=float,
        default=88.0,
        help="Pixels above this disparity percentile are treated as near.",
    )
    parser.add_argument(
        "--caution_ratio",
        type=float,
        default=0.08,
        help="Near-pixel ratio in the ROI required for CAUTION.",
    )
    parser.add_argument(
        "--danger_ratio",
        type=float,
        default=0.18,
        help="Near-pixel ratio in the ROI required for DANGER.",
    )
    return parser.parse_args()


def default_disp_path(image_path):
    base, _ = os.path.splitext(image_path)
    return f"{base}_disp.npy"


def default_output_path(image_path):
    base, _ = os.path.splitext(image_path)
    return f"{base}_warning.jpg"


def load_disparity(disp_path, width, height):
    disp = np.load(disp_path).squeeze().astype(np.float32)
    if disp.ndim != 2:
        raise ValueError(f"Expected a 2D disparity map, got shape {disp.shape}")

    disp = np.nan_to_num(disp, nan=0.0, posinf=0.0, neginf=0.0)
    if disp.shape != (height, width):
        disp = cv2.resize(disp, (width, height), interpolation=cv2.INTER_LINEAR)
    return disp


def normalize_disparity(disp):
    valid = disp[np.isfinite(disp)]
    if valid.size == 0:
        raise ValueError("Disparity map has no finite values.")

    vmin = float(np.percentile(valid, 2))
    vmax = float(np.percentile(valid, 95))
    if vmax <= vmin:
        vmax = vmin + 1e-6

    clipped = np.clip(disp, vmin, vmax)
    normalized = ((clipped - vmin) / (vmax - vmin) * 255.0).astype(np.uint8)
    return normalized


def compute_warning(disp, roi, near_percentile, caution_ratio, danger_ratio):
    x1, y1, x2, y2 = roi
    roi_disp = disp[y1:y2, x1:x2]
    valid = disp[np.isfinite(disp)]
    near_threshold = float(np.percentile(valid, near_percentile))
    near_ratio = float(np.mean(roi_disp >= near_threshold))
    mean_disp = float(np.mean(roi_disp))

    if near_ratio >= danger_ratio:
        status = "DANGER"
    elif near_ratio >= caution_ratio:
        status = "CAUTION"
    else:
        status = "SAFE"

    return status, near_ratio, mean_disp, near_threshold


def draw_warning_panel(image, status, near_ratio, mean_disp, near_threshold):
    color = STATUS_COLORS[status]
    panel = image.copy()
    cv2.rectangle(panel, (0, 0), (image.shape[1], 88), color, thickness=-1)
    cv2.addWeighted(panel, 0.78, image, 0.22, 0, dst=image)

    cv2.putText(
        image,
        f"Obstacle Warning: {status}",
        (24, 40),
        cv2.FONT_HERSHEY_SIMPLEX,
        1.0,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        image,
        f"near_ratio={near_ratio:.3f}  mean_disp={mean_disp:.3f}  threshold={near_threshold:.3f}",
        (24, 72),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.62,
        (255, 255, 255),
        1,
        cv2.LINE_AA,
    )


def draw_roi(image, roi, status):
    x1, y1, x2, y2 = roi
    color = STATUS_COLORS[status]
    overlay = image.copy()
    cv2.rectangle(overlay, (x1, y1), (x2, y2), color, thickness=-1)
    cv2.addWeighted(overlay, 0.18, image, 0.82, 0, dst=image)
    cv2.rectangle(image, (x1, y1), (x2, y2), color, thickness=3)
    cv2.putText(
        image,
        "FRONT ROI",
        (x1 + 10, max(y1 - 10, 24)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.7,
        color,
        2,
        cv2.LINE_AA,
    )


def make_comparison(image, disp_vis, annotated):
    h, w = image.shape[:2]
    separator = np.full((h, 8, 3), 245, dtype=np.uint8)
    disp_vis = cv2.resize(disp_vis, (w, h), interpolation=cv2.INTER_LINEAR)
    annotated = cv2.resize(annotated, (w, h), interpolation=cv2.INTER_LINEAR)

    cv2.putText(image, "Input", (24, h - 24), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)
    cv2.putText(
        disp_vis,
        "Predicted Disparity",
        (24, h - 24),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (255, 255, 255),
        2,
    )
    cv2.putText(
        annotated,
        "Warning Result",
        (24, h - 24),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (255, 255, 255),
        2,
    )
    return np.hstack([image, separator, disp_vis, separator, annotated])


def main():
    args = parse_args()

    image = cv2.imread(args.image_path, cv2.IMREAD_COLOR)
    if image is None:
        raise FileNotFoundError(f"Could not read image: {args.image_path}")

    height, width = image.shape[:2]
    disp_path = args.disp_path or default_disp_path(args.image_path)
    output_path = args.output_path or default_output_path(args.image_path)

    disp = load_disparity(disp_path, width, height)
    disp_norm = normalize_disparity(disp)
    disp_vis = cv2.applyColorMap(disp_norm, cv2.COLORMAP_MAGMA)

    x1 = int(width * args.roi_x1)
    x2 = int(width * args.roi_x2)
    y1 = int(height * args.roi_y1)
    y2 = int(height * args.roi_y2)
    roi = (x1, y1, x2, y2)

    status, near_ratio, mean_disp, near_threshold = compute_warning(
        disp,
        roi,
        args.near_percentile,
        args.caution_ratio,
        args.danger_ratio,
    )

    annotated = image.copy()
    draw_roi(annotated, roi, status)
    draw_warning_panel(annotated, status, near_ratio, mean_disp, near_threshold)

    comparison = make_comparison(image.copy(), disp_vis, annotated)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    cv2.imwrite(output_path, comparison)

    print(f"status={status}")
    print(f"near_ratio={near_ratio:.4f}")
    print(f"mean_disp={mean_disp:.6f}")
    print(f"near_threshold={near_threshold:.6f}")
    print(f"saved={output_path}")


if __name__ == "__main__":
    main()
